default: Pizza.java Pizzeria.java Topping.java Receipt.java
	javac Pizza.java Pizzeria.java Topping.java Receipt.java

run: Pizza.class Pizzeria.class Topping.class Receipt.class
	java Pizzeria

clean:
	rm -f *.class